name: xcms_plot
owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/xcms"
homepage_url: "https://github.com/RECETOX/galaxytools"
categories:
  - Metabolomics
description: XCMS Spectra plotting tools
long_description: |
  This suite provides tools from the XCMS package to visualize extracted ion chromatograms and raw data 
  from a single mzML file. Users can define m/z and retention time (rt) values, and the suite plots data 
  with a user-defined tolerance and rt range centered around the selected m/z and rt values.
  The MsExperiment plot function creates a two-dimensional view of three-dimensional mass spectrometry data,
  displaying peaks in the two-dimensional m/z versus retention time plane with intensity color-coding. The plot
  is saved as a PNG file
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the xcms package"
suite:
  name: suite_xcms_plot
  description: Tools for visualizing raw data and extracted ion chromatograms from mzML files. Users define
   m/z and retention time, with specified m/z tolerance in ppm and rt range."
  type: repository_suite_definition