name: waveica
owner: recetox
description: removal of batch effects for untargeted metabolomics data.
long_description: Removal of batch effects for large-scale untargeted metabolomics data based on wavelet analysis.
homepage_url: "https://github.com/dengkuistat/WaveICA/"
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/waveica"
categories:
  - Metabolomics
type: unrestricted
