name: spec2vec
owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/spec2vec"
homepage_url: "https://github.com/iomega/spec2vec"
categories:
  - Metabolomics
description: "Mass spectra similarity scoring using a trained Spec2Vec model."
long_description: |
  "Spec2Vec is a novel spectral similarity score inspired by a natural language processing algorithm—Word2Vec.
  Spec2Vec learns frag- mental relationships within a large set of spectral data to derive abstract spectral 
  embeddings that can be used to assess spectral similarities."auto_tool_repositories:
  name_template: "{{ tool_id }}"
description_template: "{{ tool_name }} tool from the spec2vec package"
suite:
  name: seuite_spec2vec
  description: tools from the spec2vec suite are used for searching mass spectral libraries and training a Spec2Vec model.
  type: repository_suite_definition