owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/riassigner"
homepage_url: "https://github.com/RECETOX/RIAssigner"
categories:
  - Metabolomics
repositories:
  riassigner:
    description: "RIAssigner is a python tool for retention index (RI) computation for GC-MS data."
    long_description: |
      "RIAssigner is a python tool for retention index (RI) computation for GC-MS data.
      Supported input data are msp and csv. Supported computational methods are piecewise linear interpolation and b-Spline interpolation."
    include:
      - riassigner.xml
      - macros.xml
      - test-data
  assign_ri_from_comment:
    description: "Assign RI from Comment Field is a tool for assigning retention indices from the comment field in csv, tsv, parquet, or msp files."
    long_description: |
      "Assign RI from Comment Field is a tool for assigning retention indices from the comment field in csv, tsv, parquet, or msp files.
      The tool will read RI from the comment field and assign them to the RI field."
    include:
      - riassigner_from_comment.xml
      - macros.xml
      - test-data
