owner: recetox
remote_repository_url: "https://github.com/UCLouvain-CBIO/scp"
homepage_url: "https://uclouvain-cbio.github.io/scp/index.html"
categories:
  - Proteomics
  - Single Cell
repositories:
  scp:
    description: "scp is a package for the single cell proteomics data processing."
    long_description: "scp is an R package for the analysis of mass spectrometry-based single cell proteomics data. It builds on the QFeatures package and allows aggregation to peptide or protein level, data transformation such as log2 transformation or normalization, batch correction and imputation of missing values. It also provides several quality control metrics."