owner: recetox
remote_repository_url: "https://github.com/RECETOX/galaxytools/tree/master/tools/matchms"
homepage_url: "https://github.com/matchms/matchms"
categories:
  - Metabolomics
repositories:
  matchms:
    description: "Calculate the similarity score and matched peaks for mass spectrometry data (MS/MS)."
    include:
      - matchms_similarity.xml
      - matchms_similarity_wrapper.py
      - test-data
      - macros.xml
  matchms_filtering:
    description: "Filter and normalize mass spectrometry data (MS/MS)."
    include:
      - matchms_filtering.xml
      - matchms_filtering_wrapper.py
      - test-data/filtering
      - macros.xml
  matchms_formatter:
    description: "Tool to reformat output tables of matchms."
    include:
      - matchms_formatter.xml
      - formatter.py
      - test-data
      - macros.xml
  matchms_networking:
    description: "Create a similarity network graph from spectral similarity scores."
    include:
      - matchms_networking.xml
      - matchms_networking_wrapper.py
      - test-data
      - macros.xml
